#!flask/bin/python
from flask import Flask, jsonify, abort, request
app = Flask(__name__)

disciplinas = [
	 {
	 'id':1,
	 'codigo':'BLU3202',
	 'nome':'Algoritimos e Estruturas de Dados',
	 'objetivos':'Apresentar os algoritmos e as estruturas de dados básicas para o desenvolvimento de programas de computador',
	 'conteudo programatico':'Análise de algoritmos • Crescimento e comportamento assintótico de funções; • Classes de comportamento assintótico; • Notação O (big O). Programação em C e Metodologias de Desenvolvimento • Consolidação de conceitos básicos de programação em C • Criação e utilização de bibliotecas de funções • Utilização de técnicas de depuração (debugging). Programação de baixo-nível • Representação de dados em memória; • Alocação dinâmica de memória; • Mecanismos de passagem de argumentos a funções. Estruturas de dados • Estruturas lineares - listas, filas e pilhas; • Tabelas de dispersão; • Árvores; • Heaps; Algoritmos de ordenação de dados • Algoritmos de Ordenação Interna: Seleção, Inserção, Shellsort, heapsort, QuickSort, Mergesort, Radixsort. • Algoritmos de Pesquisa em Memória Principal: Pesquisa Sequencial, Pesquisa Binária, Pesquisa com Transformação de Chaves, Árvores Binárias de Pesquisa.',
	 'bibliografia basica':'1. Cormen, Thomas H., Charles E. Leiserson, Ronald L. Rivest and Clifford Stein. Algoritmos: Teoria E Prática. 3 ed.: Campus, 2012. ISBN: 9788535236996. 2. Ziviani, Nivio. Projeto De Algoritmos Com Implementações Em Pascal E C 3ed.: CENGAGE, 2010. ISBN: 9788522110506. 3. Feofiloff, Paulo. Algoritmos Em Linguagem C: Campus, 2008. ISBN: 8535232494.',
	 'bibliografia complementar':'1. Wirth, Niklaus. Algoritmos E Estruturas De Dados: LTC, 1989. ISBN: 8521611900. 2. Tenenbaum, Aaron, Yedidyah Langsam and Moshe J. Augenstein. Estruturas De Dados Usando C. 1 ed.: Makron, 1995. ISBN: 8534603480. 3. Sedgewick, Robert. Algorithms in C Parts 1-4. 3 ed.: Addison Wesley, 1998. ISBN: 201314525. 4. Szwarfiter, Jayme Luiz and Lilian Markenzon. Estruturas De Dados E Seus Algoritmos. 3 ed.: LTC, 2010. ISBN: 852161750x. 5. Ziviani, Nivio. Projeto De Algoritmos Com Implementações Em Java E C++: Thomson Pioneira, 2006. ISBN: 8522105251. **** Referências 6 a 11 disponíveis no acervo eletrônico da BU-UFSC **** 6. Adamson, Iain T. Data Structures and Algorithms: A First Course. Springer, 1996. ISBN: 978-1-4471-1023-1 7. Mehlhorn, Kurt; Sanders, Peter.Algorithms and Data Structures: The Basic Toolbox. Springer-Verlag Berlin Heidelberg, 2008. ISBN: 978-3-540-77978-0 8. Storer, J. A. An Introduction to Data Structures and Algorithms. Birkhäuser Basel, 2002. ISBN: 978-1-4612-0075-8 9. Bergin, Joseph. Data Structure Programming With the Standard Template Library in C++. Springer-Verlag New York, 1998. ISBN: 978-1-4612-1630-8 10. Royce, Tony. C Programming. Complex Data Structures. Palgrave Macmillam, 1996. ISBN: 978-1-349-13759-6 11. Chapman, Arthur W. Mastering C Programming. Palgrave Macmillam, 1991. ISBN 978-1-349-11015-5'
	 },

	 {'id':2,
	 'codigo':'BLU3024',
	 'nome':'Integração de Sistemas para Automação',
	 'objetivos':'Ao final da disciplina o estudante deverá ser capaz de: • Desenvolver sistemas baseados em software para dar suporte a sistemas de automação; • Selecionar e utilizar itens de infraestrutura computacional considerando as arquiteturas e boas práticas da atualidade; • Integrar sistemas heterogêneos através de middlewares e outras ferramentas computacionais.',
	 'conteudo programatico':'Banco de Dados: • Introdução aos Sistemas Gerenciadores de Banco de Dados (SGBD); • Modelagem para banco de dados; • Álgebra Relacional e Linguagem de Consulta SQL; • No-SQL Sistemas Distribuídos: • Nuvens computacionais; • Servidores de Aplicação; • Webservers e webservices. Sistemas SCADA • Arquiteturas e aplicações dos sistemas SCADA; Projeto e prática em desenvolvimento e integração de sistemas para dar suporte a sistemas automatizados',
	 'bibliografia basica':'1. DANTAS, Mario A. R. Computação distribuída de alto desempenho: redes, clusters e grids computacionais. Rio de Janeiro: Axcel Books, 2005. 278 p. ISBN 8573232404. 2. DATE, C. J. Introdução a sistemas de bancos de dados. Rio de Janeiro: Campus, c2000. 803p. ISBN 85-7001-596-8. 3. ERL, Thomas. Cloud Computing: Concepts, Technology & Architecture. Pretience Hall. ISBN-10: 0133387526.',
	 'bibliografia complementar':'1. MCDONALD, John. Power System SCADA and Smart Grids. 2015. CRC Press. ISBN-10: 148222674X. 2. HEUSER, Carlos Alberto. Projeto de banco de dados. 6. ed. Porto Alegre: Bookman, 2009. xii, 282 p. ISBN 9788577803828. 3. SILBERSCHATZ, Abraham; KORTH, Henry F.; SUDARSHAN, S. Sistema de banco de dados. Rio de Janeiro: Elsevier, 2011. 781p. ISBN 9788535211078. 4. MARK, Dallas. SQL in a Nutshell. 2009. O Reilly. ISBN-10: 0596518846. 5. BEAULIEU, Alan. Learning SQL. O Reilly. ISBN 10:0-596-00727-2. **** Referências 6 a 11 disponíveis no acervo eletrônico da BU-UFSC **** 6. SARUKKAY, Ramesh R. Foundations of Web Technology. Springer, 2002. ISBN 978-1-4615-1135-9. 7. OELLERMANN Jr, William R. Architecting Web Services. APress MEdia, 2011. ISBN 978-1-4302-1140-2. 8. NAKHIMOVSKY, Alexander; MYERS, Tom. Google, Amazon, and Beyond: Creating and Consuming Web Services. APress Media, 2004. ISBN 978-1-4302-0818-1. 9. SPERKO, Richard. Java Persistence for Relational Databases. APress Media, 2003. ISBN 978-1-4302-0816-7. 10. ALAGIC, Suad. Relational database technology. Springer-Verlag. 1986. ISBN-13: 978-1-4612-4922-1. 11. DARIE, Cristian; WATSON, Karli; HART, Chris; HOFFMANN, Kevin; SKINNER, Julian. The Programmer s Guide to SQL. APress Media, 2003. ISBN 978-1-4302-0800-6.'
	 },

	 {'id':3,
	 'codigo':'BLU3302',
	 'nome':'Microprocessadores',
	 'objetivos':'Ao final da disciplina o estudante deverá ser capaz de: - explorar a arquitetura de microprocessadores; - explorar a programação de microprocessadores e microcontroladores, com ênfase nos conceitos independentes da inovação tecnológica.',
	 'conteudo programatico':'1. Introdução a arquitetura de microprocessadores e microcontroladores * Histórico e evolução * Conceitos básicos * Principais arquiteturas 2. Linguagem de montagem * Estrutura e principais instruções * Diretivas de Montagem * Modos de Endereçamento * Pilha e Sub-rotinas * Interrupções 3. Linguagem C em sistemas microcontrolados * Introdução Arquitetura do microcontrolador * Programação C * Temporizadores e contadores * Periféricos de E/S e portas A/D * Comunicação Serial',
	 'bibliografia basica':'1. Ziller R. Microprocessadores: Conceitos importantes, 2 ed. – Florianópolis, Edição do autor. (2000), ISBN 85-901037-2-2. Disponível em PDF. 2. Patterson, David A. and Hennessy, John L. Computer organization and design: the hardware/software interface. San Francisco: Morgan Kaufmann, 1998. 896p. 3. Morse, Stephen P. Microprocessadores 8086/8088 Arquitetura, projeto, sistemas e programação. Editora Campus, Rio de Janeiro (1988). Bibliografia alternativa para o calendário suplementar: 1. Siegfried, R. M. Computer Architecture and Organization. Lecture Notes. Online: https://home.adelphi.edu/~siegfried/cs371/notes.html 2. Bistriceanu, V. Computer Architecture Class notes. Lecture Notes. Online: http://www.cs.iit.edu/~virgil/cs470/Book/',
	 'bibliografia complementar':'1. Tanenbaum, Andew S. Organização Estruturada de Computadores. Prentice Hall do Brasil (1992), ISBN 85-7054-040-X 2. Stallings, W. Computer Organization and Architecture: Designing for Performance. Prentice Hall (2003), ISBN-13: 9780130351197 3. Morgan, Christopher L; WAITE, Mitchell. 8086/8088: manual do microprocessador de 16 bits. São Paulo: McGraw Hill, c1988. xi, 398 p. 4. Dias JR, Wilson Alonso. Microprocessadores 8086/8088: hardware & software. São Paulo: McGraw-Hill, 1990. xiv, 293p. ISBN 0074606050 5. WILLIAMS, Elliot. Make: AVR programming. 1st ed. Sebastopol: Maker Media, 2014. xviii, 453 p. ISBN 9781449355784'
	 },
	 {'id':4,
	 'codigo':'BLU3046',
	 'nome':'Sistemas Embarcados',
	 'objetivos':'Ao final da disciplina o estudante deverá: conceituar e diferenciar sistemas embarcados de outros sistemas computacionais e sua arquitetura; conhecer abordagens de modelagem de sistemas embarcados, com foco na abordagem ciberfísica; compreender questões fundamentais relacionadas a integração de software e hardware em sistemas embarcados; entender os princípios de customização de sistemas para operar de forma embarcada; utilizar ferramentas de modelagem e de simulação de sistemas embarcados; conhecer arquiteturas de softwares apropriadas para operação como sistema de tempo real; conhecer técnicas de controle, gerência e armazenamento de código fonte; obter uma visão geral sobre as licenças de software.',
	 'conteudo programatico':'1. Introdução aos SEs. - Principais componentes; - Arquiteturas; - Exemplos de aplicação. 2. Modelagem de SE - Revisão das possíveis abordagens para modelagem de SEs (em camadas, em ciclos, de integração hardware e software, entre outras); - A abordagem Ciber-física (fundamentos/elementos, modelagem contínua, discreta, modelo ciberfísico). 3. Arquiteturas de SEs para tempo real. - Esquemas de escalonamento com e sem prioridade; - Escalonamento de tarefas dependentes (compartilhamento de recursos e relação de precedência); - Suporte de aplicações para tempo real (aspectos funcionais e temporais). 4. Ferramentas para simulação de SEs. - Qemu. - OVPsim. - Outras ferramentas. 5. Customização de sistemas operacionais para plataformas dedicadas (drivers de dispositivos, bibliotecas e aplicações); - Visão geral de uma distribuição de sistema operacional: Diagrama de blocos e compreensão dos módulos de hardware exigidos; - Fluxo de desenvolvimento de sistemas operacionais (toolchains e bibliotecas do sistema); - Ferramentas de configuração e geração de distribuíções (compilação, instalação e execução). 6. Técnicas de controle, gerência e armazenamento de código-fonte. - Repositório de fontes local, centralizado e distribuído. - Sistemas de versionamento de fontes (SVN e GIT). 7. Visão geral sobre licenças de software. - Leis de propriedade de software no Brasil. - Licenças proprietárias versus licenças de softwre livre. - GPL e suas variantes. - Licenças estilo Apache e BSD.',
	 'bibliografia basica':'1. E. A. Lee and S. A. Seshia. Introduction to Embedded Systems - A Cyber-Physical Systems Approach (Links to an external site.)Links to an external site., Second Edition, MIT Press, 2017. 2. Marwedel, P. Embedded System Design: Embedded Systems Foundations of Cyber-Physical Systems, Springer. 2010. 3. OLIVEIRA, André Schneider de; ANDRADE, Fernando Souza de. Sistemas embarcados: hardware e firmware na prática. 2. ed. São Paulo: Érica, 2010. 316 p. ISBN 9788536501055.',
	 'bibliografia complementar':'1. Zurell, K. First Steps with Embedded Systems. Byte Craft Limited, Waterloo, 2002. 2. HOBOKEN, W. Raspberry Pi Projects. Andrew Robinson Editor, 2013. 3. LOVE, R. Linux system programming: talking directly to the kernel and C library. 2ed., OReilly Media; 2013. 4. Taha. W. Lecture Notes on Cyber Physical Systems. 5. YAGHMOUR, Karim et al. Construindo sistemas linux embarcados. 2. ed. Rio de Janeiro: Alta Books, 2009. xix, 377 p. ISBN 9788576083436.'
	 },
	 {'id':5,
	 'codigo':'BLU3101',
	 'nome':'Introdução à Informática para Automação',
	 'objetivos':'Ao final da disciplina o estudante deverá: - Conhecer de forma geral as partes principais do hardware e os procedimentos gerais para criação do software do sistema computacional; - Compreender o conceito de algoritmos e utilizar as técnicas básicas de desenvolvimento; - Reconhecer a estrutura de um programa; - Utilizar o computador como ferramenta de trabalho na solução de problemas, aplicando os conceitos básicos de programação na elaboração de programas.',
	 'conteudo programatico':'1. Introdução, programas de computador, linguagens de programação; 2. Algoritmos; 3. Tipos de dados, variáveis e constantes; 4. Expressões lógicas; 5. Estruturas de seleção: se e caso; 6. Estruturas de controle: repetição; 7. Vetores; 8. Matrizes; 9. Tratamento de Strings; 10. Registros; 11. Modularização (funções e procedimentos); 12. Operações com arquivos.',
	 'bibliografia basica':'1. Forbellone, A. L. V. Lógica de Programação. 3 ed.: Prentice Hall Brasil, 2005. ISBN:8576050242 2. Boratti, Isaias C. e Oliveira, A. B. Introdução a Programação – Algoritmos. 4 ed.: Visual Books, 2013. ISBN: 9788575022832 3. Deitel, Harvey; Paul Deitel. C - Como Programar. 6 ed.: Pearson Brasil, 2011. ISBN: 8576059347',
	 'bibliografia complementar':'1. Schildt, Herbert. C Completo e Total. 3 ed.: Makron Books, 2006. ISBN: 8534605955 2. Brian W. Kernighan e Dennis M. Ritchie. C, a Linguagem de Programação: padrão ANSI. Campus Editora, 1989. ISBN: 8570015860 3. De Sá, Marques, Lidel, Zamboni. Fundamentos de programação usando C. 4 ed.: FCA, 2004. ISBN: 972722475x 4. Ascenio, Ana Fernanda Gomes e Campos, Edilene Aparecida Veneruchi. Fundamentos da programação de computadores: algoritmos, Pascal, C/C++ e Java. 3 ed.: Prentice HALL Brasil, 2012. ISBN: 9788564574168 5. Holloway, J. P. Introdução à Programação para Engenharia: Resolvendo Problemas com Algoritmos. LTC, 2006. ISBN: 8521614535'
	 },
	 {'id':6,
	 'codigo':'BLU3023',
	 'nome':'Programação Orientada de Objetos',
	 'objetivos':'Apresentar os algoritmos e as estruturas de dados básicas para o desenvolvimento de programas de computador. Ao final da disciplina o estudante deverá ser capaz de: • Compreender os conceitos necessários para programação orientada a objetos; • Aplicar metodologias e técnicas orientadas a objetos para desenvolvimento de programas de computador; • Capacitar o aluno a análise de diagramas de classe e implementação de um programa de computador; • Conhecer e saber aplicar os conceitos de programação orientada a objetos.',
	 'conteudo programatico':'Elementos básicos de programação orientada a objetos:  Classes e objetos  Encapsulamento  Agregação  Herança  Polimorfismo  Interfaces Metodologias para análise e programação orientada a objetos:  Diagrama de Classes UML  Noções de padrões de projetos orientados a objetos Prática em programação orientada a objetos  Prática com a linguagem Java',
	 'bibliografia basica':'1. DEITEL, Paul J.; DEITEL, Harvey M. Java: como programar. 10. ed. São Paulo: Pearson Prentice Hall, 2016. xxvii, 818 p. ISBN 9788543019055 2. DEITEL, Harvey M.; DEITEL, Paul J. C++: como programar. 9. ed. São Paulo: Pearson Prentice Hall, 2014. xlii, 1163 p. ISBN 9780133378719. 3. BARKER, Jacquie. Beginning Java Objects: From Concepts to Code. Second Edition. Berkeley: Apress, Inc., 2005. ISBN 9781430200369.',
	 'bibliografia complementar':'1. PREISS, Bruno R. Estruturas de dados e algoritmos: padroes de projetos orientados a objetos com java. Rio de Janeiro: Campus, c2001. xvi, 566p. ISBN 8535206930. 2. BORATTI, Isaias Camilo. Programação orientada a objetos em JAVA. Florianópolis: Visual Books, 2007. 310p. ISBN 9788575021996. 3. ISAYAMA, Helder. Programação Orientada a Objetos. 2015. ISBN-10: 8536510803 4. WAZLAWICK, Raul Sidnei. Análise e projeto de sistemas de informação orientados a objetos. 2. ed. rev. e atual. Rio de Janeiro: Elsevier: Campus, 2011. 330 p. (Série Editora Campus, SBC). ISBN 9788535239164. 5. PREISS, Bruno R. Data structures and algorithms: with object-oriented design patterns in C++. New York: J. Wiley & Sons, 1999. xvii, 660 p. ISBN 9780471241348 6. MENDES, Antonioi. Introdução à Programação Orientada a Objetos Com C++. 2011.'
	 },
	 {'id':7,
	 'codigo':'BLU3401',
	 'nome':'Sinais e Sistemas Lineares',
	 'objetivos':'Dotar o aluno de ferramentas que possibilitem a análise de sinais e da dinâmica de sistemas lineares utilizando representações na forma entrada-saída; introduzir o problema de controle de sistemas dinâmicos e noções de filtragem.',
	 'conteudo programatico':'Sinais • Conceito de sinais: sinais de tempo contínuo, discreto e amostrado • Propriedades dos sinais • Classificação dos sinais • Operações de sinais • Modelos básicos de sinais Sistemas • Conceito de sistema • Classificação de Sistemas • Sistemas Lineares invariantes no tempo (LTI) contínuos e discretos • Exemplos Análise de sistemas LTI contínuos e discretos no tempo • Resposta a entrada nula • Resposta ao impulso • Convolução • Reposta total • Estabilidade interna e Bibo estabilidade • Resposta à exponencial de duração infinita • Relação entre os casos contínuo e discreto Análise de sistemas LTI contínuos usando transformada de Laplace: • Definição da transformada • Propriedades • Determinação das transformadas inversas • Solução de equações diferenciais • Função de transferência, polos e zeros • Estabilidade, influência de polos e zeros na resposta temporal Análise de sistemas LTI contínuos usando transformada Z: • Definição da transformada • Propriedades • Determinação das transformadas inversas • Solução de equações a diferença • Função de transferência, polos e zeros • Estabilidade, influência de polos e zeros na resposta temporal Álgebra de blocos e aplicações Resposta em frequência: • Diagrama polar e análise via diagramas de Bode • Propriedades de Filtragem de sistemas LIT • Amostragem e filtragem digital de sinais contínuos no tempo • Natureza periódica da resposta em frequência de sistemas discretos, alising e taxa de amostragem • Introdução ao controle digital de sistemas contínuos no tempo, princípios de projeto de controladores discretos no tempo.',
	 'bibliografia basica':'1. Lathi, B. P. Sinais e Sistemas Lineares. 2 ed.: Bookman, 2007. ISBN: 9788560031139. 2. OPPENHEIM, Alan V; WILLSKY, Alan S; NAWAB, Syed Hamid. Sinais e Sistemas Lineares 2ed.: Prentice-Hall, 2010. ISBN: 9788576055044. 3. Gene F. Franklin; J. David Powell; Abbas Emami-Naini. Sistemas de Controle para Engenharia 6ed. Porto Alegre: Bookman, 2013. 4. Apostilas e material digital disponibilizado na plaforma de estudos.',
	 'bibliografia complementar':'1. HAYKIN, Simon S; VAN VEEN, Barry. Sinais e Sistemas. 1ed:Bookman, 2001. ISBN: 9788573077414. 2. Roberts, M.J. Fundamentos em Sinais e Sistemas: MCGRAW HILL - ARTMED, 2009. ISBN: 9788577260386. 3. Hwei Hsu. Sinais e Sistemas. 2 ed.: Bookman, 2012. ISBN: 9788577809387. 4. VAN DE VEGTE, Joyce. Fundamentals of digital signal processing. 1 ed.: Prentice-Hall, 2002. ISBN: 9780130160775. 5. ALAN V. OPPENHEIM E RONALD W. SCHAFER. PROCESSAMENTO EM TEMPO DISCRETO DE SINAIS. 3 ed.: PEARSON BRASIL, 2013. ISBN: 9788581431024.'
	 },
	 {'id':8,
	 'codigo':'BLU3604',
	 'nome':'Acionamentos Elétricos',
	 'objetivos':'Introduzir os conceitos acionamentos elétricos, apresentando as características gerais de motores, dispositivos elétricos, fusíveis, comando elétricos, partida de motores e chaves de partida eletrônicas. Além disso, o aluno aprenderá sobre máquinas de corrente contínua, máquinas de corrente alternada, servomotores e noções de controle de máquinas.',
	 'conteudo programatico':'1. Dispositivos de acionamentos 2. Acionamentos de motores com chaves de partida mecânicas 3. Acionamentos de motores com chaves de partida eletrônica 4. Máquinas de corrente contínua 5. Máquinas de corrente alternada 6. Servomotores 7. Noções de controle de máquinas',
	 'bibliografia basica':'1. FRANCHI, Claiton Moro. Sistemas de acionamento elétrico. 1. ed. São Paulo: Érica, c2014. 152 p. 2. FRANCHI, Claiton Moro. Acionamentos elétricos. 5. ed. rev. São Paulo: Érica, c2007. 252 p. 3 HART, Daniel W. Eletrônica de potência: análise e projetos e circuitos. Porto Alegre: AMGH, 2012. xvi, 478 p.',
	 'bibliografia complementar':'1. Frank Petruzella. Motores Elétricos e Acionamentos. Bookman Editora, 2013. 2. B.K. BOSE - Power Electronics and Drives. Prentice-Hall, USA, 1986. 3. W. LEONHARD - Control of Electrical Drives. Springer-Verlag, Germany, 1985. 4. B. W. Williams. Power Electronics: Devices, Drivers and Applications. Wiley, 1987. 5. UMANS, de FITZGERALD e KINGSLEY Stephen. Máquinas Elétricas - 7ª Ed., Bookman, 2014.'
	 },
	 {'id':9,
	 'codigo':'BLU3602',
	 'nome':'Sistemas de Controle',
	 'objetivos':'Fornecer a metodologia de trabalho e os métodos clássicos de projeto para a solução de problemas de controle monovariável. Aprendizado de: métodos de análise e projeto de controladores de uma entrada uma saída. Entender os princípios de funcionamento e operação dos controladores industriais. Saber configurar diversas estruturas de controle: realimentação, pré-alimentação, cascata, relação, etc. entendendo a importância de cada uma. Perceber a importância da modelagem para a análise e o projeto de sistemas de controle e a problemática associada aos erros de modelagem. Aplicar os conceitos de análise e projeto tanto a sistemas contínuos como discretos. Entender manuais de operação de controladores industriais e saber configurá-los para uma dada situação prática.',
	 'conteudo programatico':'1. Revisão do conteúdo necessário da disciplina Sinais e Sistemas Lineares 2. Parte 1 Introdução: 2a. Sistemas contínuos/discretos/amostrados. Objetivos de controle. Controle com dois graus de liberdade. 2b. Respostas de sistemas no domínio do tempo e na freqüência. Sistemas com zeros, fase não-mínima e com atraso de transporte. 2c. Estabilidade de sistemas. 3. Parte 2 Métodos de Projeto: 3a. Lugar das raízes 3b. Lugar das raízes como ferramenta de projeto. 3c. Projeto de sistemas de controle contínuos e discretos. 3d. Rejeição de perturbações e seguimento de referências em sistemas de controle. 3e. Controladores por realimentação e pré-alimentação 4. Parte 3 Controladores Industriais: 4a. Controladores PID: estruturas, técnicas de ajuste e implementação prática. 4b. PID industriais 5. Parte 4 Conteúdos adicionais: 5a. Introdução ao controle robusto. 5b. Compensação de sistemas com atraso, Preditor de Smith e modificações.',
	 'bibliografia basica':'FRANKLIN, Gene F., POWELL, J. D., Sistemas de Controle para Engenharia, Ed. Bookman, 6ª edição, 2013. OGATA, Katsuhiro, Engenharia de Controle Moderno, Ed. Prentice Hall, 5ª edição, 2010. NISE, N., Engenharia de Sistemas de Controle, Editora LTC, 6ª Ed., 2012.',
	 'bibliografia complementar':'ASTROM, K.J., HAGGLUND, T., Advanced PID control, Ed. Instrument Society, 1ª edição, 2005. BAZZANELLA, A., Sistemas de Controle: Princípios e Métodos de Projeto, Ed. UFRGS, 1ª edição, 2014. DORF, Richard C., e BISHOP, R. H.. Sistemas de Controle Modernos, Editora LTC, 12ª Ed., 2013. NORMEY-RICO, J.E., Apostila Sistemas de Controle, disponível online. PHILLIPS, C. L., NAGLE, H. T., DIGITAL CONTROL SYSTEM ANALYSIS AND DESIGN, Prentice Hall, 4ª ed., 2014.'
	 },
	 {'id': 10,
	 'codigo': 'BLU3014',
	 'nome':'Eletrônica de Potência',
	 'objetivos':'Ao final da disciplina o estudante deverá ser capaz de: •entender as diferenças construtivas e de aplicações dos diversos semicondutores de potência; •dimensionar semicondutores de potência para aplicações em eletrônica de potência; •calcular componentes harmônicas de corrente e tensão de retificadores e inversores; •conhecer os diversos retificadores e suas aplicações; •conhecer os diversos conversores CC-CC e suas aplicações; •conhecer os diversos inversores e suas aplicações; •fazer cálculo térmico de semicondutores de potência; •projetar elementos magnéticos para conversores estáticos de potência; •simular e experimentar os diversos conversores estáticos de potência; •dimensionar e experimentar circuitos de comando e controle para conversores estáticos.',
	 'conteudo programatico':'1.Dispositivos Semicondutores de Potência 1.1 Diodos 1.2 Tiristores 1.3 Transistores: Bipolar, MOSFET, IGBT 1.4 Outros componentes emergentes 2. Simulação de Conversores Estáticos 2.1 Conceitos fundamentais 2.2 Simuladores computacionais: LTSpice, Orcad, PSim 2.3 Uso de simuladores 3. Componentes Harmônicas 3.1 Caracterização de sinais elétricos 3.2 Definição de potência em circuitos lineares e circuitos não lineares 3.3 A Série de Fourier e cálculos de harmônicas 3.4 Fator de potência e distorção harmônica total 4. Retificadores 4.1 Retificadores de meia onda controlados e não controlados monofásicos e trifásicos 4.2 Retificadores de onda completa controlados e não controlados monofásicos e trifásicos 5. Controladores de Tensão Alternada 5.1 Controlador de tensão alternada monofásico: gradador 5.2 Controlador de tensão alternada trifásico 5.3 Aplicações de controladores de tensão alternada 6. Conversores CC-CC 6.1 Conceitos fundamentais 6.2 Conversores CC-CC básicos não isolados: buck, boost, buck-boost, Cuk, sepic e zeta 6.3 Conversores intercalados 7. Fontes Chaveadas 7.1 Conceitos fundamentais 7.2 Fontes chaveadas convencionais: flyback, forward, push-pull, half-bridge e full-bridge 7.3 Controle de fontes chaveadas 8. Inversores 8.1 Conceitos fundamentais 8.2 Inversores half-bridge, full-bridge e de múltiplos níveis 8.3 Modulações de inversores 9. Assessórios para Conversores Estáticos 9.1 Circuitos de comando 9.2 Circuitos snubbers e grampeadores 9.3 Dissipadores de calor',
	 'bibliografia basica':'1. HART, Daniel W. Eletrônica de Potência: Análise e Projetos de Circuitos. Porto Alegre: McGraw-Hill, 2012. 2. BARBI, Ivo. Eletrônica de potência. 7. ed. Florianópolis: Edição do Autor, 2013. 3. BARBI, Ivo; MARTINS, Denizar Cruz. Eletrônica de potência: conversores CC-CC básicos não isolados. 2. ed. Florianopolis: Ed. dos Autores, 2006. Adicional para acesso on-line: 4. Robert W. Erickson, Dragan Maksimović. Fundamentals of Power Electronics. 2ed. Springer. 2001. https://link.springer.com/book/10.1007%2Fb100747 - acesse via VPN UFSC. 5. Euzeli dos Santos; Edison R. da Silva. Advanced Power Electronics Converters: PWM Converters Processing AC Voltages. Wiley-IEEE Press. 2014. http://ieeexplore.ieee.org/servlet/opac?bknumber=7022272 - acesse via VPN UFSC. 6. Mohamed E. El-Hawary. Principles of Electric Machines with Power Electronic Applications. Wiley-IEEE Press. 2002. http://ieeexplore.ieee.org/servlet/opac?bknumber=5264263 - acesse via VPN UFSC.',
	 'bibliografia complementar':'1. BARBI, Ivo. Eletrônica de potência: projetos de fontes chaveadas. 2. ed. Florianópolis: Edição do Autor, 2005. 2. KREIN, Philip T. Elements of power electronics. New York: Oxford University, 1998. 3. ERICKSON, R.W., MAKSIMOVIC, D. Fundamentals of Power Electronics, 2nd ed. Kluwer Academic Publishers, Dordrecht (2001) 4. MOHAN, Ned; UNDELAND, Tore M; ROBBINS, William P. Power electronics: converters, applications, and design. 3rd ed. New York: John Wiley, 2003. 5. RASHID, M. H. Eletrônica de potência: circuitos, dispositivos e aplicações. São Paulo: MakronBooks, 1999. Adicional para acesso on-line: 6. Bimal K. Bose. Power Electronics and Variable Frequency Drives: Technology and Applications. Wiley-IEEE Press. 1997. http://ieeexplore.ieee.org/servlet/opac?bknumber=5263964 - acesse via VPN UFSC. 7. Derek A. Paice. Power Electronics Converter Harmonics: Multipulse Methods for Clean Power. Wiley-IEEE Press. 1996. http://ieeexplore.ieee.org/servlet/opac?bknumber=5263984 - acesse via VPN UFSC. 8. Haitham Abu-Rub; Mariusz Malinowski; Kamal Al-Haddad. Power Electronics for Renewable Energy Systems, Transportation and Industrial Applications. Wiley-IEEE. 2014. http://ieeexplore.ieee.org/servlet/opac?bknumber=7753049 - acesse via VPN UFSC.'
	 	 },
     ]

@app.route('/disciplinas/getdisciplina', methods=['GET'])
def get_disciplinas():
 return jsonify({'disciplinas':disciplinas})


@app.route('/disciplinas/getdisciplina/<string:disciplina_id>', methods=['GET'])
def get_disciplina(disciplina_id):
    a = None
    for disciplina in disciplinas:
        if disciplina['codigo'] == disciplina_id:
            a = disciplina
    if a == None:
        abort(404)
    return jsonify(a)


@app.route('/disciplinas', methods=['POST'])
def create_disciplina():
#	if not request.json or not 'nome' in request.json or not 'curso' in request.json:
#		abort(400)
	disciplina = { 'id': disciplinas[-1]['id']+1,
		'codigo': request.json['codigo'],
		'nome': request.json['nome'],
		'objetivos': request.json['objetivos'],
		'conteudo programatico': request.json['conteudo programatico'],
		'bibliografia basica': request.json['bibliografia basica'],
		'bibliografia complementar': request.json['bibliografia complementar']
		}
	disciplinas.append(disciplina)
	return jsonify({'disciplina':disciplina}),201


if __name__ == '__main__':
    app.run(host='localhost', port=8081, debug=True)
    
#curl --header "Content-Type: application/json" --request POST --data '{"codigo":"BLU3333","nome":"DisciplinaX","objetivos":"objetivoX","conteudo programatico":"conteudoX","bibliografia basica":"Livro1","bibliografia complementar":"Livro2"}' http://localhost:8081/disciplinas    
